language: objective-c

notifications:
  email: false

env:
 global:
  - EnableNuGetPackageRestore=true 
 matrix:
  - MONO_VER="3.1.12"

before_install:
 - wget "http://download.mono-project.com/archive/${MONO_VER}/macos-10-x86/MonoFramework-MDK-${MONO_VER}.macos10.xamarin.x86.pkg"
 - sudo installer -pkg "MonoFramework-MDK-${MONO_VER}.macos10.xamarin.x86.pkg" -target /

script:
 - xbuild FailessLib.fsproj