language: objective-c

notifications:
  email: false

env:
 global:
  - EnableNuGetPackageRestore=true 
 matrix:
  - MONO_VER="3.2.4"

before_install:
 - wget "http://download.mono-project.com/archive/${MONO_VER}/macos-10-x86/MonoFramework-MDK-${MONO_VER}.macos10.xamarin.x86.pkg"
 - sudo installer -pkg "MonoFramework-MDK-${MONO_VER}.macos10.xamarin.x86.pkg" -target /
 
 - wget "http://github.com/fsharp/fsharp/raw/master/lib/bootstrap/4.0/Microsoft.FSharp.targets"
 
 - wget "http://github.com/fsharp/fsharp/raw/master/lib/bootstrap/4.0/FSharp.Build.dll"
 - wget "http://github.com/fsharp/fsharp/raw/master/lib/bootstrap/4.0/FSharp.Core.dll"
 - wget "http://github.com/fsharp/fsharp/raw/master/lib/bootstrap/4.0/FSharp.Core.dll.optdata"
 - wget "http://github.com/fsharp/fsharp/raw/master/lib/bootstrap/4.0/FSharp.Core.dll.sigdata"
 
 - sudo mv FSharp.Build.dll /usr/local/lib/mono/4.0/FSharp.Build.dll
 - sudo mv FSharp.Core.dll /usr/local/lib/mono/4.0/FSharp.Core.dll
 - sudo mv FSharp.Core.dll.optdata /usr/local/lib/mono/4.0/FSharp.Core.dll.optdata
 - sudo mv FSharp.Core.dll.sigdata /usr/local/lib/mono/4.0/FSharp.Core.dll.sigdata

script:
 - xbuild FailessLib-mono.fsproj